Update adventages.html
1mposs1blee/chocolate-team-project pull request #1
Opened 2023-03-24 17:48 UTC by Tamira2804

2023-03-24 20:20 UTC, 1mposs1blee requested changes

2023-03-24 20:20 UTC, 1mposs1blee commented on src/partials/adventages.html
> +    <h1 hidden>adventages</h1>
Тут лучше сделать h2 заголовок, дабы иерархию последовательности заголовков не нарушать, ибо h1 по идее у нас должен быть скрыт в hero

2023-03-24 20:20 UTC, 1mposs1blee commented on src/partials/adventages.html
> +          <use href="../img/sprite.svg#"></use>
Уже можно добавить нужные иконки, sprite.svg залит)

2023-03-24 20:34 UTC, Tamira2804 commented on src/partials/adventages.html
> +    <h1 hidden>adventages</h1>
Изменила

2023-03-25 10:19 UTC, 1mposs1blee approved these changes

2023-03-25 10:20 UTC, merged