Header html
1mposs1blee/chocolate-team-project pull request #10
Opened 2023-03-25 16:05 UTC by bodikzilvova

2023-03-25 21:07 UTC, 1mposs1blee requested changes

2023-03-25 21:07 UTC, 1mposs1blee commented on src/css/header.css
> +.burger-close-icon{
вижу, что, например, кнопка закрытия мобильного меню для телефона - размером 12х12 в самом макете

2023-03-26 15:32 UTC, bodikzilvova commented on src/css/header.css
> +.container {
Виправив)

2023-03-26 15:32 UTC, bodikzilvova commented on src/partials/header.html
> +      <a class="header-logo" href="./index.html">SIMPLY CHOCOLATE
Виправив)

2023-03-26 15:32 UTC, bodikzilvova commented on src/partials/header.html
> +  <ul class="header-item">
Виправив)

2023-03-26 15:33 UTC, bodikzilvova commented on src/partials/header.html
> +    <li class="header-link">
Виправив)

2023-03-26 15:33 UTC, bodikzilvova commented on src/partials/header.html
> +    <a class="" href="https://www.instagram.com/" lang="en"
Виправив)

2023-03-26 15:33 UTC, bodikzilvova commented on src/partials/header.html
> +    </div>
Виправив, всі подальші теж)

2023-03-27 17:53 UTC, closed without merging